name = "Beyond The Wake"
author = "TeamAurorisla"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c308e516d0b404248aab5db1ad02d966ce9676e50dca9cbd74176044f0dcf56d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.243"
