name = "Beyond The Wake"
author = "TeamAurorisla"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93e75c513ddeea71334e5ffe1bd71765bfa29fa0b9078ba3d9b8b2e352096072"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.243"
