name = "Beyond The Wake"
author = "TeamAurorisla"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8a2f83505bf9108517a4c1677d5673a5aae77457ee161b86cc9971ac8f29e33"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.243"
